### ISSUE TITLE
刚刚看到了个消息持久化插件，可供历史记录功能的实现，大佬有兴趣嘛

### ISSUE THREAD

**Issue by FlyRenxing** [only52607/mi-re-do#3]
刚刚看到了个消息持久化插件，可供历史记录功能的实现，大佬有兴趣嘛？
地址：
[mirai-hibernate-plugin](https://github.com/cssxsh/mirai-hibernate-plugin)

**Comment by only52607** [comment]
目前暂时没有更新打算，后续会考虑添加
